package pt.alcancebus.passes;
import android.app.*;import android.content.*;import android.graphics.Color;import android.nfc.NfcAdapter;import android.os.*;import android.widget.*;import java.io.*;import java.net.*;import org.json.*;
public class MainActivity extends Activity{
 static final String SERVER="https://COLOCAR-ENDERECO-RENDER.onrender.com",TOKEN="COLOCAR_DEVICE_TOKEN",DEVICE="BUS 01";
 NfcAdapter nfc;PendingIntent pi;TextView status,person;Spinner line,dir;long tripId=0;
 String[] lines={"Linha 1 — Santa Marta - São Pedro - Rossas","Linha 2 — Anjos - Agra - Rossas"},dirs={"Ida","Volta"};
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);person=findViewById(R.id.person);line=findViewById(R.id.line);dir=findViewById(R.id.direction);line.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,lines));dir.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,dirs));findViewById(R.id.start).setOnClickListener(v->startTrip());findViewById(R.id.list).setOnClickListener(v->showList());nfc=NfcAdapter.getDefaultAdapter(this);Intent i=new Intent(this,getClass()).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);int f=PendingIntent.FLAG_UPDATE_CURRENT;if(Build.VERSION.SDK_INT>=31)f|=PendingIntent.FLAG_MUTABLE;pi=PendingIntent.getActivity(this,0,i,f);}
 void startTrip(){try{JSONObject j=new JSONObject();j.put("device",DEVICE);j.put("line",lines[line.getSelectedItemPosition()]);j.put("direction",dirs[dir.getSelectedItemPosition()]);j.put("token",TOKEN);post("/api/trip/start",j,r->{tripId=r.optLong("trip_id");status.setText("ENCOSTE O PASSE");line.setEnabled(false);dir.setEnabled(false);});}catch(Exception e){}}
 protected void onResume(){super.onResume();if(nfc!=null&&nfc.isEnabled())nfc.enableForegroundDispatch(this,pi,null,null);}protected void onPause(){super.onPause();if(nfc!=null)nfc.disableForegroundDispatch(this);}
 protected void onNewIntent(Intent i){super.onNewIntent(i);if(tripId==0){status.setText("INICIE A VIAGEM");return;}byte[] id=i.getByteArrayExtra(NfcAdapter.EXTRA_ID);if(id==null)return;StringBuilder s=new StringBuilder();for(byte x:id)s.append(String.format("%02X",x));try{JSONObject j=new JSONObject();j.put("trip_id",tripId);j.put("card_uid",s.toString());j.put("token",TOKEN);post("/api/validate",j,r->{String q=r.optString("result"),name=r.optString("name"),num=r.optString("pass_number");status.setText(q.equals("JA_LIDO")?"PASSE JÁ LIDO":q);status.setTextColor(q.equals("VALIDO")?Color.rgb(0,130,60):Color.RED);person.setText(name+(num.isEmpty()?"":" — Passe "+num));});}catch(Exception e){}}
 void showList(){if(tripId==0)return;new Thread(()->{try{URL u=new URL(SERVER+"/api/trip/"+tripId+"/passengers?token_value="+URLEncoder.encode(TOKEN,"UTF-8"));BufferedReader b=new BufferedReader(new InputStreamReader(u.openStream()));StringBuilder s=new StringBuilder();String x;while((x=b.readLine())!=null)s.append(x);JSONArray a=new JSONArray(s.toString());StringBuilder m=new StringBuilder();for(int k=0;k<a.length();k++){JSONObject o=a.getJSONObject(k);m.append(o.optString("time")).append("  ").append(o.optString("name")).append(" — ").append(o.optString("pass_number")).append("\n");}runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Passageiros desta viagem").setMessage(m.toString()).setPositiveButton("Fechar",null).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Sem ligação",Toast.LENGTH_SHORT).show());}}).start();}
 interface CB{void done(JSONObject r);}void post(String p,JSONObject j,CB cb){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(SERVER+p).openConnection();c.setRequestMethod("POST");c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);c.getOutputStream().write(j.toString().getBytes("UTF-8"));BufferedReader b=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String x;while((x=b.readLine())!=null)s.append(x);JSONObject r=new JSONObject(s.toString());runOnUiThread(()->cb.done(r));}catch(Exception e){runOnUiThread(()->{status.setText("SEM LIGAÇÃO");status.setTextColor(Color.RED);});}}).start();}
}